### ISSUE TITLE
Import the new versions

### ISSUE THREAD

**Issue by zedtux** [werein/flexslider-rails#1]
Can you please update the flexslider version ? It looks like the current one is 2.6 and this gem has 2.2.

Also align the gem version with the library version in order to ease the life of Rails devs :-)

**Comment by jirikolarik** [comment]
I'm no longer maintaining this repo, use https://rails-assets.org instead. 

``` ruby
source 'https://rails-assets.org' do
  gem 'rails-assets-flexslider'
end
```

Or open PR with these updates

**Comment by zedtux** [comment]
Sorry no way for rails-assets.org.

I can help on this as I'm maintaining some gems like [bootstrap-slider-rails](https://github.com/YourCursus/bootstrap-slider-rails), [switchery-rails](https://github.com/YourCursus/switchery-rails), [perfect-scrollbar-rails](https://github.com/YourCursus/perfect-scrollbar-rails) and [fakerjs-rails](https://github.com/YourCursus/fakerjs-rails).

Do you have some skills with Docker ?

**Comment by zedtux** [comment]
Repo no more maintained as said by @jirikolarik ... closing the issue.

**Comment by jirikolarik** [comment]
I can add you as a maintainer if you'd like

**Comment by zedtux** [comment]
Thank you @jirikolarik but I used another library so that I'm not using this one anymore.

**Comment by jirikolarik** [comment]
Alrighty then :)
